apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-feedback-local

resources:
  - namespace.yaml
  - ../../base
  - pvc.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml

images:
  - name: real-time-nlp-api
    newName: real-time-nlp-api
    newTag: local
