apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-feedback

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: serviceaccount-patch.yaml

images:
  - name: real-time-nlp-api
    newName: REPLACE_WITH_ECR_REGISTRY/real-time-nlp-api
    newTag: REPLACE_WITH_GIT_SHA
