apiVersion: v1
kind: Service
metadata:
  name: feedback-api
  labels:
    app.kubernetes.io/name: feedback-api
    app.kubernetes.io/component: serving
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: feedback-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
